import { useMemo, useState } from 'react';
import { Button } from '../../components/Button';
import { MetricCard } from '../../components/MetricCard';
import { Panel, SectionTitle, FieldLabel } from '../../components/Panel';
import { Pill } from '../../components/StatusBadge';
import { Icon } from '../../components/Icon';
import { HorseAvatar } from '../horses/HorseAvatar';
import { ConfirmDialog } from '../../components/ConfirmDialog';
import { useRtms } from '../../app/RtmsContext';
import { ADMISSION_STAGE_LABELS, type AdmissionStage } from '../../app/access';
import { ADMISSION_DOCUMENT_LABELS, ADMISSION_DOCUMENT_TYPES, REQUIRED_ADMISSION_DOCUMENTS, type Candidate, type CandidateStatus, type RacingReadinessAssessment } from './candidateData';
import { REGULAR_STALLS } from '../stables/stableData';

const tone: Record<CandidateStatus, 'neutral' | 'info' | 'warning' | 'success' | 'danger'> = { GROOM_REVIEW: 'info', WAITING_FOR_STALL: 'warning', VET_REVIEW: 'info', TRAINER_REVIEW: 'info', MANAGER_REVIEW: 'warning', APPROVED: 'success', REJECTED: 'danger' };
const stages: AdmissionStage[] = ['GROOM_REVIEW', 'VET_REVIEW', 'TRAINER_REVIEW', 'MANAGER_REVIEW'];

export function CandidatesSection() {
  const { navigate, toast, candidates: records, getCandidateStatus, can, reviewGroomAdmission, approveVeterinaryAdmission, submitReadinessAssessment, rejectCandidate, approveCandidate, horses, currentUser } = useRtms();
  const availableSlots = REGULAR_STALLS.filter((slot) => !horses.some((horse) => horse.stable === slot.stable && horse.stall === slot.stall));
  const [selectedId, setSelectedId] = useState('cand-1'); const [confirm, setConfirm] = useState<'groom' | 'vet' | 'manager' | 'reject' | null>(null); const [slot, setSlot] = useState('');
  const [assessment, setAssessment] = useState({ status: 'READY' as RacingReadinessAssessment['status'], conformationScore: '', temperamentScore: '', gaitQualityScore: '', estimatedMonthsToRace: '', remarks: '' });
  const candidates = useMemo(() => records.map((candidate) => ({ ...candidate, evaluation: getCandidateStatus(candidate) })), [records, getCandidateStatus]);
  const selected = candidates.find((candidate) => candidate.id === selectedId) ?? candidates[0]; const stage = selected?.evaluation as CandidateStatus | undefined;
  const updateAssessment = (field: keyof typeof assessment, value: string) => setAssessment((current) => ({ ...current, [field]: value }));
  function sendAssessment() { if (!selected || !assessment.remarks.trim()) { toast('Add assessment remarks before sending to the Manager.', 'warning'); return; } const number = (value: string, maximum: number) => value === '' ? undefined : Number(value); const scores = [number(assessment.conformationScore, 10), number(assessment.temperamentScore, 10), number(assessment.gaitQualityScore, 10)]; const months = number(assessment.estimatedMonthsToRace, 60); if (scores.some((score) => score !== undefined && (!Number.isFinite(score) || score < 0 || score > 10)) || months !== undefined && (!Number.isFinite(months) || months < 0 || months > 60)) { toast('Scores must be 0–10 and estimated months must be 0–60.', 'warning'); return; } submitReadinessAssessment(selected, { status: assessment.status, conformationScore: scores[0], temperamentScore: scores[1], gaitQualityScore: scores[2], estimatedMonthsToRace: months, remarks: assessment.remarks.trim(), assessedAt: new Date().toLocaleDateString('en-GB'), trainer: currentUser.name }); }
  return <><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><MetricCard label="Applications" value={candidates.length} unit="total" icon="users" /><MetricCard label="Awaiting my review" value={candidates.filter((item) => (item.evaluation === 'GROOM_REVIEW' && can('admission.review.groom')) || (item.evaluation === 'VET_REVIEW' && can('admission.review.vet')) || (item.evaluation === 'TRAINER_REVIEW' && can('admission.assess.trainer')) || (item.evaluation === 'MANAGER_REVIEW' && can('admission.approve'))).length} unit="applications" icon="clock" tone="info" /><MetricCard label="In quarantine" value={candidates.filter((item) => item.horseId && item.evaluation !== 'APPROVED' && item.evaluation !== 'REJECTED').length} unit="Candidates" icon="building" tone="warning" /><MetricCard label="Eligible" value={candidates.filter((item) => item.evaluation === 'APPROVED').length} unit="horses" icon="check" tone="success" /></div>
    <div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,350px)_minmax(0,1fr)]"><Panel className="overflow-hidden"><div className="border-b border-[var(--color-border)] px-3 py-2.5"><SectionTitle>Admission applications</SectionTitle></div><ul className="divide-y divide-[var(--color-border)]">{candidates.map((candidate) => <li key={candidate.id}><button onClick={() => setSelectedId(candidate.id)} className={'flex w-full items-center gap-2.5 px-3 py-2.5 text-left ' + (candidate.id === selected?.id ? 'bg-[var(--color-primary-subtle)]' : 'hover:bg-[var(--color-surface-subtle)]')}><HorseAvatar name={candidate.name} image={candidate.image} size={38} /><span className="min-w-0 flex-1"><span className="block truncate text-[13px] font-medium">{candidate.name}</span><span className="block truncate text-[11px] text-[var(--color-text-muted)]">{candidate.owner}</span></span><Pill tone={tone[candidate.evaluation]} size="sm">{ADMISSION_STAGE_LABELS[candidate.evaluation]}</Pill></button></li>)}</ul></Panel>
      {selected && <div className="space-y-4"><Panel padded><div className="flex gap-3"><HorseAvatar name={selected.name} image={selected.image} size={56} rounded="md" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-[17px] font-semibold">{selected.name}</h2><Pill tone={tone[selected.evaluation]}>{ADMISSION_STAGE_LABELS[selected.evaluation]}</Pill></div><div className="mt-2 grid grid-cols-2 gap-x-6 gap-y-1 text-[12px] text-[var(--color-text-secondary)]"><span>{selected.breed} · {selected.sex}</span><span>Owner: {selected.owner}</span><span>Registration: {selected.registrationNumber ?? 'Not recorded'}</span><span>{selected.stable && selected.stall ? `${selected.stable} · ${selected.stall}` : 'Awaiting quarantine'}</span></div></div></div></Panel>
        <Panel padded><SectionTitle>Admission path</SectionTitle><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4">{stages.map((item, index) => { const current = stages.indexOf(selected.evaluation as AdmissionStage); const done = selected.evaluation === 'APPROVED' || current > index; const active = selected.evaluation === item || (item === 'GROOM_REVIEW' && selected.evaluation === 'WAITING_FOR_STALL'); return <div key={item} className={'rounded-[var(--radius-sm)] border px-2 py-2 text-[11px] ' + (active ? 'border-[var(--color-primary)] bg-[var(--color-primary-subtle)]' : done ? 'border-[var(--color-success)]/40 bg-[var(--color-success-soft)]' : 'border-[var(--color-border)]')}><Icon name={done ? 'check' : active ? 'clock' : 'minus'} size={12} className="mr-1 inline" />{ADMISSION_STAGE_LABELS[item]}</div>; })}</div><p className="mt-3 text-[12px] text-[var(--color-text-secondary)]">{selected.evaluation === 'WAITING_FOR_STALL' ? 'Groom review passed; a quarantine slot is required before the Candidate horse can be created.' : selected.evaluation === 'APPROVED' ? `Eligible and assigned to ${selected.stable} ${selected.stall}.` : 'Candidate remains in quarantine until Manager approval.'}</p></Panel>
        <div className="grid gap-4 lg:grid-cols-2"><Panel padded><SectionTitle>Horse documents</SectionTitle><div className="mt-3 space-y-2">{ADMISSION_DOCUMENT_TYPES.map((type) => { const document = selected.documents?.find((item) => item.type === type); return <div key={type} className="flex items-center justify-between gap-2 text-[12px]"><span>{document ? <Icon name="check" size={13} className="mr-1 inline text-[var(--color-success)]" /> : <Icon name="minus" size={13} className="mr-1 inline text-[var(--color-text-muted)]" />}{ADMISSION_DOCUMENT_LABELS[type]}{REQUIRED_ADMISSION_DOCUMENTS.includes(type) && ' *'}</span>{document ? <button className="max-w-32 truncate text-[var(--color-primary)] hover:underline" onClick={() => document.file && window.open(URL.createObjectURL(document.file), '_blank')}>{document.fileName}</button> : <span className="text-[var(--color-text-muted)]">Not supplied</span>}</div>; })}</div></Panel><Panel padded><SectionTitle>Veterinary handoff</SectionTitle>{selected.examSchedule ? <div className="mt-3 text-[12px] text-[var(--color-text-secondary)]"><p className="font-medium text-[var(--color-text-primary)]">{selected.examSchedule.description}</p><p className="mt-1">{selected.examSchedule.status === 'COMPLETED' ? `Completed ${selected.examSchedule.scheduledDate ?? ''}` : 'Pending — date to be arranged'}</p>{selected.horseId && <button className="mt-3 text-[var(--color-primary)] hover:underline" onClick={() => navigate('veterinary', { view: 'examine', horseId: selected.horseId })}>Open medical dossier / record exam</button>}</div> : <p className="mt-3 text-[12px] text-[var(--color-text-muted)]">Created after Groom accepts and assigns quarantine.</p>}</Panel></div>
        {selected.readinessAssessment && <Panel padded><SectionTitle>Racing readiness assessment</SectionTitle><div className="mt-2 grid grid-cols-2 gap-2 text-[12px] text-[var(--color-text-secondary)]"><span>Status: <b>{selected.readinessAssessment.status}</b></span><span>Trainer: {selected.readinessAssessment.trainer}</span><span>Conformation: {selected.readinessAssessment.conformationScore ?? '—'}/10</span><span>Gait: {selected.readinessAssessment.gaitQualityScore ?? '—'}/10</span></div><p className="mt-2 text-[12px]">{selected.readinessAssessment.remarks}</p></Panel>}
        {stage === 'TRAINER_REVIEW' && can('admission.assess.trainer') && <Panel padded><SectionTitle>Create racing readiness assessment</SectionTitle><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-5"><select value={assessment.status} onChange={(event) => updateAssessment('status', event.target.value)} className="h-9 rounded border border-[var(--color-border)] px-2 text-[12px]"><option>READY</option><option>NEEDS_MORE_TRAINING</option><option>UNSUITABLE</option></select>{(['conformationScore', 'temperamentScore', 'gaitQualityScore', 'estimatedMonthsToRace'] as const).map((field) => <input key={field} value={assessment[field]} type="number" min="0" max={field === 'estimatedMonthsToRace' ? 60 : 10} onChange={(event) => updateAssessment(field, event.target.value)} placeholder={field === 'estimatedMonthsToRace' ? 'Months' : '0–10'} className="h-9 rounded border border-[var(--color-border)] px-2 text-[12px]" />)}</div><textarea value={assessment.remarks} onChange={(event) => updateAssessment('remarks', event.target.value)} placeholder="Assessment remarks" className="mt-3 min-h-20 w-full rounded border border-[var(--color-border)] p-2 text-[12px]" /><Button className="mt-3" variant="primary" icon="file-text" onClick={sendAssessment}>Send assessment to Manager</Button></Panel>}
        {stage === 'MANAGER_REVIEW' && can('admission.approve') && <Panel padded><SectionTitle>Regular stable assignment</SectionTitle><div className="mt-3 flex flex-wrap gap-2"><select value={slot} onChange={(event) => setSlot(event.target.value)} className="h-9 rounded border border-[var(--color-border)] px-2 text-[12px]"><option value="">Select an available slot</option>{availableSlots.map((item) => <option key={`${item.stable}-${item.stall}`} value={`${item.stable} · ${item.stall}`}>{item.stable} · {item.stall}</option>)}</select><Button variant="primary" icon="check" disabled={!slot} onClick={() => setConfirm('manager')}>Approve & mark eligible</Button></div></Panel>}
        <div className="flex flex-wrap gap-2">{stage === 'GROOM_REVIEW' || stage === 'WAITING_FOR_STALL' ? can('admission.review.groom') && <Button variant="primary" icon="check" onClick={() => setConfirm('groom')}>{stage === 'WAITING_FOR_STALL' ? 'Retry quarantine placement' : 'Accept & create Candidate'}</Button> : null}{stage === 'VET_REVIEW' && can('admission.review.vet') && <Button variant="primary" icon="check" onClick={() => setConfirm('vet')}>Approve veterinary review</Button>}{stage !== undefined && !['APPROVED', 'REJECTED', 'TRAINER_REVIEW'].includes(stage) && ((stage === 'GROOM_REVIEW' && can('admission.review.groom')) || (stage === 'VET_REVIEW' && can('admission.review.vet')) || (stage === 'MANAGER_REVIEW' && can('admission.approve'))) && <Button variant="destructive" icon="x" onClick={() => setConfirm('reject')}>Reject</Button>}</div>
      </div>}</div>
    <ConfirmDialog open={confirm === 'groom'} title={`Accept ${selected?.name}?`} description="This creates a Candidate horse, places it in quarantine, and sends the initial medical dossier to Veterinary." confirmLabel="Create Candidate" onCancel={() => setConfirm(null)} onConfirm={() => { if (selected) reviewGroomAdmission(selected); setConfirm(null); }} /><ConfirmDialog open={confirm === 'vet'} title="Approve veterinary review?" description="The initial examination must have been recorded in the medical dossier." confirmLabel="Approve review" onCancel={() => setConfirm(null)} onConfirm={() => { if (selected) approveVeterinaryAdmission(selected); setConfirm(null); }} /><ConfirmDialog open={confirm === 'manager'} title="Mark this horse eligible?" description="This releases the quarantine slot and assigns the selected regular stable slot." confirmLabel="Approve & assign" onCancel={() => setConfirm(null)} onConfirm={() => { if (selected) { const [stable, stall] = slot.split(' · '); approveCandidate(selected, stable, stall); } setConfirm(null); }} /><ConfirmDialog open={confirm === 'reject'} tone="danger" title={`Reject ${selected?.name ?? 'application'}?`} description="The admission will be closed and any Candidate horse will be released from quarantine." confirmLabel="Reject admission" onCancel={() => setConfirm(null)} onConfirm={() => { if (selected) rejectCandidate(selected); setConfirm(null); }} />
  </>;
}
